server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingService
    username: root
    password: Drc@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8085