server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingService
    username: root
    password: Drc@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
   import: optional:configserver:http://localhost:8085

#okta:
#  oauth2:
#    issuer: https://dev-27743248.okta.com/oauth2/default
#    audience: api://default

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
